export const SUPABASE_URL = 'https://xoiexytawfnvttwmuaxg.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvaWV4eXRhd2ZudnR0d211YXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NjkzMTAsImV4cCI6MjA4OTM0NTMxMH0.B1TdpVh9qEtEM4u06D2cISWfvYF-S66_ePzywlqxQAM';
